all:
  children:
    routers:
      children:
        vios_group:
          hosts:
            RTR2:
              ansible_become: 'true'
              ansible_become_method: enable
              ansible_become_password: admin
              ansible_connection: ansible.netcommon.network_cli
              ansible_host: 192.168.79.11
              ansible_network_os: cisco.ios.ios
              ansible_password: admin
              ansible_user: admin
