---
- name: PlaybookDevices
  hosts: Devices
  # gather_facts : false
  tasks:
    - name: Print ansible config location
      ansible.builtin.debug:
        msg:
          - "{{ ansible_config_file }}"
          #- "{{ inventory_file }}"
          #- "{{ inventory_host }}"
          - "{{ ansible_facts.net_hostname }}"
          - "{{ ansible_facts.net_version }}"
    - name: Change Domain 
      cisco.ios.ios_config:
        lines: ip domain name {{ ip_domain_name }}
        save_when: changed
      register: ip_domain_config

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ ip_domain_config }}"
        